import type { Metadata } from "next";
import "./globals.css";
import GlobalCursorGlow from "@/components/GlobalCursorGlow";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <GlobalCursorGlow />
        {children}
      </body>
    </html>
  );
}
